#!/usr/bin/env node
/**
 * check-skills.mjs — drift check for the Vercel skills CLI layout.
 *
 * Layout:
 *   skills/               → source of truth (hand-edited)
 *   .claude/skills/       → generated copy for Claude Code
 *   .agents/skills/       → generated copy for Codex, Cursor, Antigravity (shared)
 *   skills-lock.json      → lockfile generated by `skills add`
 *
 * The copies are produced by `pnpm skills:install`
 * (= `skills add ./skills --skill '*' -a claude-code -a codex -a cursor -a antigravity -y --copy`).
 * We commit all three trees so fresh clones work immediately.
 *
 * Modes:
 *   node scripts/check-skills.mjs              → fail on drift
 *   node scripts/check-skills.mjs --bootstrap  → silently run pnpm skills:install
 *                                                on a fresh clone if the copies
 *                                                are missing (postinstall).
 *
 * Drift conditions that fail:
 *   1. skills-lock.json missing while skills/ is populated.
 *   2. A name in skills/ is not listed in the lockfile (or vice versa).
 *   3. .claude/skills/<name>/ or .agents/skills/<name>/ missing.
 *   4. Any file differs between skills/<name>/ and its target copies.
 */
import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  existsSync,
  readFileSync,
  readdirSync,
  statSync,
  lstatSync,
} from "node:fs";
import { join, relative, resolve } from "node:path";

const ROOT = resolve(new URL("..", import.meta.url).pathname);
const SRC = join(ROOT, "skills");
const LOCK = join(ROOT, "skills-lock.json");
const TARGETS = {
  "claude-code": join(ROOT, ".claude", "skills"),
  "codex-cursor-antigravity": join(ROOT, ".agents", "skills"),
};

const isBootstrap = process.argv.includes("--bootstrap");

function fail(msg) {
  console.error(`check-skills: ${msg}`);
  process.exit(1);
}

function hashDir(dir) {
  // Deterministic content hash of a directory tree (sorted relative paths + contents).
  const files = [];
  const walk = (d) => {
    for (const name of readdirSync(d).sort()) {
      const p = join(d, name);
      const s = lstatSync(p);
      if (s.isDirectory()) walk(p);
      else if (s.isFile()) files.push(p);
    }
  };
  walk(dir);
  const h = createHash("sha256");
  for (const p of files) {
    h.update(relative(dir, p));
    h.update("\0");
    h.update(readFileSync(p));
    h.update("\0");
  }
  return h.digest("hex");
}

function bootstrap() {
  // Fresh clone safety net: if someone deleted/never had the target copies,
  // rebuild them from skills/ without failing the install on error.
  if (!existsSync(SRC)) return;
  const needed = Object.values(TARGETS).some((t) => !existsSync(t));
  if (!needed) return;
  try {
    execSync("pnpm run skills:install", { cwd: ROOT, stdio: "inherit" });
  } catch {
    // postinstall must not block `pnpm install`; surface it via skills:check.
  }
}

if (isBootstrap) {
  bootstrap();
  process.exit(0);
}

if (!existsSync(SRC)) fail("skills/ missing — nothing to check");
if (!existsSync(LOCK)) fail("skills-lock.json missing — run `pnpm skills:install` after adding skills");

const sourceSkills = readdirSync(SRC)
  .filter((n) => statSync(join(SRC, n)).isDirectory())
  .sort();

const lock = JSON.parse(readFileSync(LOCK, "utf8"));
const lockNames = new Set(Object.keys(lock.skills ?? {}));

const missingInLock = sourceSkills.filter((n) => !lockNames.has(n));
if (missingInLock.length) {
  fail(
    `skills/ has entries missing from skills-lock.json: ${missingInLock.join(", ")}.\n` +
      `Run: pnpm skills:add ./skills/<name> -a claude-code -a codex -a cursor -a antigravity`
  );
}

const extraInLock = [...lockNames].filter((n) => !sourceSkills.includes(n));
if (extraInLock.length) {
  fail(
    `skills-lock.json has entries not in skills/: ${extraInLock.join(", ")}.\n` +
      `Run: pnpm exec skills remove -s ${extraInLock.join(" -s ")} -y`
  );
}

for (const [label, target] of Object.entries(TARGETS)) {
  if (!existsSync(target)) {
    fail(`${target} missing (${label}) — run \`pnpm skills:install\``);
  }
  for (const name of sourceSkills) {
    const srcPath = join(SRC, name);
    const tgtPath = join(target, name);
    if (!existsSync(tgtPath)) {
      fail(`${tgtPath} missing — run \`pnpm skills:install\``);
    }
    if (hashDir(srcPath) !== hashDir(tgtPath)) {
      fail(
        `drift: ${relative(ROOT, tgtPath)} differs from ${relative(ROOT, srcPath)}.\n` +
          `Run: pnpm skills:install`
      );
    }
  }
}

console.log(`skills: OK (${sourceSkills.length} skills in sync across targets)`);
